spring:
  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/bank
    hikari:
      schema: public
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  servlet:
    context-path: /api/v1
springdoc:
  api-docs:
    path: /api-docs